# Generated by Django 4.1 on 2022-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_cliente_apellido_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
