# Generated by Django 4.0.6 on 2022-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
