# Generated by Django 4.0.6 on 2022-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('C', 'Classic'), ('G', 'Gold'), ('B', 'Black')], max_length=1),
        ),
    ]
