# Generated by Django 4.0.6 on 2022-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.IntegerField(default=models.IntegerField(unique=True, verbose_name='DNI')),
        ),
    ]
