# Generated by Django 4.0.6 on 2022-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_alter_cliente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
