# Generated by Django 4.0.6 on 2022-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_cliente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
